### ISSUE TITLE
Cannot register new performance counters after first init

### ISSUE THREAD

**Issue by diequeeq** [petabridge/akka-monitoring#32]
Steps to reproduce:
1. Ensure Akka category name DOES NOT exists in PerformanceCounters
2. Start demo app as admin with default configuration:
`ActorMonitoringExtension.RegisterMonitor(actorSystem, new ActorPerformanceCountersMonitor(customMetrics));`
3. Ensure Akka category name exists in PerformanceCounters
4. Stop demo app
5. Add custom counters to the demo app, eg.:
`var registeredMonitor = ActorMonitoringExtension.RegisterMonitor(_system,
    new ActorPerformanceCountersMonitor(
        new CustomMetrics
        {
            Counters = { "akka.custom.metric1"},
            Gauges = { "akka.messageboxsize"},
            Timers = { "akka.handlertime" }
        }));
`
6. Start demo app as admin.

Expected: new performance counters "akka.custom.metric1", "akka.messageboxsize" and "akka.handlertime" created and seen in Performance Monitor

Actual: new performance counters are not created

**Comment by diequeeq** [comment]
As a quick workaround I suggest to:
1. Open registry editor
2. Find and delete everything under "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\Akka"
3. Start application as admin to recreate new set of counters.

**Comment by Aaronontheweb** [comment]
We address this in the readme:

> One gotcha to be aware of is that .NET performance counters cannot be added to an existing category. If you have to add counters to categories that already exist, the only way you can do so is to delete the category and re-create it with all of its contents. So if you find that you are adding custom metrics and nothing is appearing in Perfmon then you may need to delete the Akka performance counter category. Additionally, performance counters don't always show up straightaway so you may need to give it some time. To delete the Counter category you can remove the following key in the windows registry:

HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\Akka\Performance (not recommended in production code!)

**Comment by diequeeq** [comment]
I think this one may be closed. The issue is documented in readme as @Aaronontheweb mentioned.
