### ISSUE TITLE
StatsD - Target .Net Standard 2.0

### ISSUE THREAD

**Issue by alfredherr** [petabridge/akka-monitoring#39]
I'm using the StatsD monitoring package (Akka.Monitoring.StatsD 0.7.0). 

I'm getting the following warning: 

"warning NU1701: Package 'Akka.Monitoring 0.7.0' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.0'. This package may not be fully compatible with your project."

Can you guys recompile  targeting .Net Standard 2.0?

**Comment by mikebridge** [comment]
+1 for netstandard2.0
